# Generated by Django 2.0.13 on 2025-10-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_auto_20210228_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='generated_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='invite_generated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
