FROM mysql:5.7

RUN apt-get update \
    && apt-get install -y wget\
        libdbd-mysql-perl libterm-readkey-perl

RUN wget percona.com/get/pt-table-sync -P /usr/bin/
RUN chmod +x /usr/bin/pt-table-sync

COPY scripts /usr/src
