# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-28 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='filename_extensions',
            field=models.ManyToManyField(blank=True, related_name='filename_extensions_set', to='courses.FilenameExtension'),
        ),
        migrations.AlterField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='issue_fields',
            field=models.ManyToManyField(blank=True, to='issues.IssueField'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='course_teachers_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='years.Year'),
        ),
        migrations.AlterField(
            model_name='coursemarksystem',
            name='marks',
            field=models.ManyToManyField(blank=True, to='courses.MarkField'),
        ),
    ]
