# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('courses', '0005_auto_20210319_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EasyCIRequesites',
            new_name='EasyCIParams',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='easyCI_integrated',
            new_name='easyCI',
        ),
    ]
