# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210319_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyciparams',
            name='command',
            field=models.CharField(default='q', max_length=191),
            preserve_default=False,
        ),
    ]
