# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_easyciparams_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='easyCI',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.DeleteModel(
            name='EasyCIParams',
        ),
    ]
