# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-02 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210320_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='easyCI',
            new_name='easyCI_url',
        ),
    ]
