# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-24 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210402_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_new_python_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.CASCADE, to='years.Year'),
        ),
    ]
