# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-05 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210402_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_costudents',
            field=models.BooleanField(default=False),
        ),
    ]
