# Generated by Django 2.0.13 on 2025-10-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20230305_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group_with_extern',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_with_extern', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='issue_status_system',
            field=models.ForeignKey(db_index=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='issues.IssueStatusSystem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mark_system',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseMarkSystem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(default=2025, on_delete=django.db.models.deletion.CASCADE, to='years.Year'),
        ),
        migrations.AlterField(
            model_name='defaultteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='defaultteacher',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='defaultteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcoursemark',
            name='course',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='studentcoursemark',
            name='mark',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.MarkField'),
        ),
        migrations.AlterField(
            model_name='studentcoursemark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcoursemark',
            name='teacher',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_change_mark', to=settings.AUTH_USER_MODEL),
        ),
    ]
