# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:27
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'novyj'), ('rework', 'na_dorabotke'), ('verification', 'na_proverke'), ('accepted', 'zachteno'), ('auto_verification', 'na_avtomaticheskoj_proverke'), ('need_info', 'trebuetsja_informacija')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuefield',
            name='plugin',
            field=models.CharField(default='FieldDefaultPlugin', max_length=191),
        ),
        migrations.AlterField(
            model_name='issuefield',
            name='plugin_version',
            field=models.CharField(default='0.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='color',
            field=colorfield.fields.ColorField(default='#818A91', max_length=18),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='tag',
            field=models.CharField(blank=True, choices=[('rework', 'rework'), ('verification', 'verification'), ('accepted', 'accepted'), ('seminar', 'seminar'), ('accepted_after_deadline', 'accepted_after_deadline')], max_length=191, null=True),
        ),
    ]
