# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-05 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0007_auto_20210228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='costudents',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='costudents', to=settings.AUTH_USER_MODEL),
        ),
    ]
