# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20210228_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(blank=True, max_length=2500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Event')),
            ],
        ),
    ]
