# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-22 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20210228_1721'),
        ('issues', '0007_auto_20200612_1427'),
    ]

    operations = [
    ]
