# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-24 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('command_tasks', '0001_initial'),
        ('issues', '0007_auto_20210228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='command_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='command_tasks.CommandTask'),
        ),
        migrations.AddField(
            model_name='issue',
            name='second_student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='third_student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
