# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-02 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_merge_20220122_1951'),
        ('issues', '0008_issue_costudents'),
    ]

    operations = [
    ]
