# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-26 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_merge_20230402_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sended_notify',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='costudents',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='costudents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('rework', 'На доработке'), ('verification', 'На проверке'), ('accepted', 'Зачтено'), ('auto_verification', 'На автоматической проверке'), ('need_info', 'Требуется информация')], default='new', max_length=20),
        ),
    ]
