# Generated by Django 2.0.13 on 2025-10-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20240226_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issues.IssueField'),
        ),
        migrations.AlterField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
        migrations.AlterField(
            model_name='file',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Event'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issues.IssueStatus'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
