# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='_message_recipients_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='_message_recipients_user_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
