# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-28 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients_course',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients_group',
            field=models.ManyToManyField(blank=True, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients_status',
            field=models.ManyToManyField(blank=True, to='users.UserStatus'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients_user',
            field=models.ManyToManyField(blank=True, related_name='_message_recipients_user_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
