# Generated by Django 2.0.13 on 2025-10-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_merge_20220122_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients_user',
            field=models.ManyToManyField(blank=True, related_name='_message_recipients_user_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender+', to=settings.AUTH_USER_MODEL),
        ),
    ]
