# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-02-26 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anycontest', '0002_auto_20200328_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='got_verdict',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
