# Generated by Django 2.0.13 on 2025-10-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anycontest', '0003_auto_20240226_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.File'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
    ]
