#!/bin/bash

mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute="
    CREATE DATABASE $DATABASE_NAME;
    CREATE USER '$DATABASE_USERNAME'@'%' IDENTIFIED BY '$DATABASE_PASSWORD';
    GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$DATABASE_USERNAME'@'%';
    GRANT ALL PRIVILEGES ON test_$MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';"

