# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_messages',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='send_notify_messages',
            field=models.ManyToManyField(blank=True, related_name='send_notify_messages', to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, related_name='unread_messages', to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='users_by_status', to='users.UserStatus'),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='deleted_messages',
            field=models.ManyToManyField(blank=True, related_name='log_deleted_messages', to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='send_notify_messages',
            field=models.ManyToManyField(blank=True, related_name='log_send_notify_messages', to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, related_name='log_unread_messages', to='mail.Message'),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='user_status',
            field=models.ManyToManyField(blank=True, db_index=True, to='users.UserStatus'),
        ),
    ]
