# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:27
from __future__ import unicode_literals

import anytask.storage
import colorfield.fields
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='academic_degree',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='academic_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=anytask.storage.OverwriteStorage(), upload_to=users.models.get_upload_path, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='ru', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time_zone',
            field=models.TextField(default='Europe/Moscow'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ya_contest_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ya_contest_oauth',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ya_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ya_passport_email',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ya_passport_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ya_passport_oauth',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='academic_degree',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='academic_title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=anytask.storage.OverwriteStorage(), upload_to=users.models.get_upload_path, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='language',
            field=models.CharField(blank=True, default='ru', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='position',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='ya_contest_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='ya_contest_oauth',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='ya_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='ya_passport_email',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='ya_passport_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilelog',
            name='ya_passport_oauth',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='color',
            field=colorfield.fields.ColorField(default='#818A91', max_length=18),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='tag',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('extramural', 'extramural'), ('fulltime', 'fulltime'), ('not_active', 'not_active'), ('academic', 'academic')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='type',
            field=models.CharField(blank=True, choices=[('activity', 'status_studenta'), ('filial', 'filial'), ('admission', 'status_postupleniya')], max_length=191, null=True),
        ),
    ]
