# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-24 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_in_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_uid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofilelog',
            name='notify_in_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilelog',
            name='telegram_uid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
