# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-22 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210424_1055'),
        ('users', '0003_auto_20200612_1427'),
    ]

    operations = [
    ]
