dist: bionic
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
    pip install -r test-requirements.txt

before_script:
  - rm -rf build

script:
  - make lint && tox

after_success:
  - coveralls
