# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
