# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('All', 's_obsuzhdeniem'), ('Only mark', 'tolko_ocenka'), ('Material', 'material'), ('Seminar', 'seminar'), ('Jupyter Notebook', 'jupyter notebook')], default='All', max_length=128),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='type',
            field=models.CharField(choices=[('All', 's_obsuzhdeniem'), ('Only mark', 'tolko_ocenka')], default='All', max_length=128),
        ),
        migrations.AlterField(
            model_name='tasktaken',
            name='status_check',
            field=models.CharField(choices=[('EDIT', 'Дорешивание'), ('QUEUE', 'Ожидает проверки'), ('OK', 'Задача зачтена и/или больше не принимается')], db_index=True, default='EDIT', max_length=5),
        ),
    ]
