# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210228_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_costudents',
            field=models.IntegerField(default=0),
        ),
    ]
