# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-02 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_max_costudents'),
        ('tasks', '0004_merge_20220122_1951'),
    ]

    operations = [
    ]
