# Generated by Django 2.0.13 on 2025-10-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210228_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='years.Year'),
        ),
    ]
