# This workflow deploy beta anytask locally

name: Deploy local beta

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependencies
        run: pip3 install virtualenv
      - name: Deploy
        run: source deploy_local_beta/run.sh --python-path=python3
