# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='period',
            field=models.CharField(choices=[('Once', 'odin_raz'), ('Weekly', 'ezhenedelno')], default='Once', max_length=128),
        ),
    ]
